FROM almalinux:9
ADD https://github.com/pdevpos/tools-automation/blob/main/variables.tf /tmp/sample1.txt
ADD https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip /tmp/frontend1.txt
CMD ["sleep", "1000"]